# Generated by Django 4.2.7 on 2023-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('ownername', models.CharField(max_length=100)),
                ('NumberofEmployees', models.IntegerField()),
            ],
            options={
                'db_table': 'business',
            },
        ),
    ]
